
-create a new folder
-Rename folder to datasessions
-Go to folder datasession
-_File_-> _new terminal_
Terminal commands
'''sh
git status
git init
git status
'''
-_File_-> _New NOtebook
-Rename_Untitled.ipynb_to_day1.ipynb
Teminal commands
'''sh
git status
'''
-_File_-> _New Text File_
-Add''' .ipynb_checkpoints/to text file
-Rename Untitled.
'''

#NUmpy Basics

In [1]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

In [5]:
np.array

<function numpy.array>

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [7]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [8]:
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the me

In [9]:
arr1=np.array([1,2,3])

In [10]:
arr1

array([1, 2, 3])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1.ndim

1

In [13]:
arr1.shape

(3,)

In [15]:
arr1.size

3

In [16]:
len(arr1)

3

In [17]:
arr2=np.arange(1,7).reshape(2,3)

In [18]:
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 3)

In [21]:
arr2.size

6

In [22]:
len(arr2)

2

In [24]:
arr2.nbytes

24

In [25]:
arr2.dtype

dtype('int32')

In [27]:
arr2.itemsize


4

In [28]:
arr2.size*arr2.itemsize

24

In [30]:
arr11=np.random.randint(1,30)

In [31]:
arr11

11

In [34]:
temp=np.random.randint(1,30, 50)

In [33]:
arr11

array([27, 25,  9, 19,  8, 16, 11, 28,  1, 21, 10,  3, 21, 12, 11, 16, 22,
        3,  9,  1, 25, 28, 17, 17, 11,  3, 20, 25, 16, 19,  3, 10, 23,  7,
       20,  3, 10, 12, 15, 24, 21, 17, 13, 29, 27,  4, 16,  2, 28, 17])

In [35]:
temp.mean()

14.04

In [36]:
temp.max()

29

In [37]:
temp.min()

1

In [38]:
np.median(temp)

14.5

In [39]:
temp.prod()


0

In [40]:
temp.prod()

0

In [41]:
temp

array([17,  7, 18,  1,  2,  8, 21, 18,  1, 18,  2,  3, 17, 15,  5,  4, 19,
       12, 25, 28, 26,  9,  4, 13, 19,  9, 25, 22,  4, 18, 18, 14,  2, 29,
        4, 24,  9, 12, 14, 18, 24, 18, 14, 22, 26, 27,  2,  9, 23,  3])

In [46]:
temp.prod()

0

In [43]:
temp.min()

1

In [44]:
help(temp.prod)

Help on built-in function prod:

prod(...) method of numpy.ndarray instance
    a.prod(axis=None, dtype=None, out=None, keepdims=False)
    
    Return the product of the array elements over the given axis
    
    Refer to `numpy.prod` for full documentation.
    
    See Also
    --------
    numpy.prod : equivalent function



In [47]:
arr11


array([27, 25,  9, 19,  8, 16, 11, 28,  1, 21, 10,  3, 21, 12, 11, 16, 22,
        3,  9,  1, 25, 28, 17, 17, 11,  3, 20, 25, 16, 19,  3, 10, 23,  7,
       20,  3, 10, 12, 15, 24, 21, 17, 13, 29, 27,  4, 16,  2, 28, 17])

In [48]:
arr11.prod()

0

In [49]:
np.prod(temp)

0

In [50]:
np.__version__

'1.16.2'

In [51]:
temp.cumsum()

array([ 17,  24,  42,  43,  45,  53,  74,  92,  93, 111, 113, 116, 133,
       148, 153, 157, 176, 188, 213, 241, 267, 276, 280, 293, 312, 321,
       346, 368, 372, 390, 408, 422, 424, 453, 457, 481, 490, 502, 516,
       534, 558, 576, 590, 612, 638, 665, 667, 676, 699, 702], dtype=int32)

In [52]:
temp

array([17,  7, 18,  1,  2,  8, 21, 18,  1, 18,  2,  3, 17, 15,  5,  4, 19,
       12, 25, 28, 26,  9,  4, 13, 19,  9, 25, 22,  4, 18, 18, 14,  2, 29,
        4, 24,  9, 12, 14, 18, 24, 18, 14, 22, 26, 27,  2,  9, 23,  3])

In [53]:
temp.std()

8.47339365307667

In [55]:
np.sum(temp)

702

In [56]:
temp1=temp.reshape(2,25)

In [58]:
temp1


array([[17,  7, 18,  1,  2,  8, 21, 18,  1, 18,  2,  3, 17, 15,  5,  4,
        19, 12, 25, 28, 26,  9,  4, 13, 19],
       [ 9, 25, 22,  4, 18, 18, 14,  2, 29,  4, 24,  9, 12, 14, 18, 24,
        18, 14, 22, 26, 27,  2,  9, 23,  3]])

In [59]:
temp1.mean()

14.04

In [61]:
np.median(temp1)

14.5

In [62]:
temp1.std()

8.47339365307667

In [63]:
temp1.sum()

702

In [64]:
temp1.cumsum()

array([ 17,  24,  42,  43,  45,  53,  74,  92,  93, 111, 113, 116, 133,
       148, 153, 157, 176, 188, 213, 241, 267, 276, 280, 293, 312, 321,
       346, 368, 372, 390, 408, 422, 424, 453, 457, 481, 490, 502, 516,
       534, 558, 576, 590, 612, 638, 665, 667, 676, 699, 702], dtype=int32)

In [65]:
temp1


array([[17,  7, 18,  1,  2,  8, 21, 18,  1, 18,  2,  3, 17, 15,  5,  4,
        19, 12, 25, 28, 26,  9,  4, 13, 19],
       [ 9, 25, 22,  4, 18, 18, 14,  2, 29,  4, 24,  9, 12, 14, 18, 24,
        18, 14, 22, 26, 27,  2,  9, 23,  3]])

In [66]:
np.mean(temp1, axis=0)

array([13. , 16. , 20. ,  2.5, 10. , 13. , 17.5, 10. , 15. , 11. , 13. ,
        6. , 14.5, 14.5, 11.5, 14. , 18.5, 13. , 23.5, 27. , 26.5,  5.5,
        6.5, 18. , 11. ])

In [67]:
np.mean(temp1, axis=1)

array([12.48, 15.6 ])

np.sum(temp2)

In [68]:
np.sum(temp1, axis=1)

array([312, 390])

In [69]:
temp2=temp.reshape(2,5,5)

In [70]:
temp2

array([[[17,  7, 18,  1,  2],
        [ 8, 21, 18,  1, 18],
        [ 2,  3, 17, 15,  5],
        [ 4, 19, 12, 25, 28],
        [26,  9,  4, 13, 19]],

       [[ 9, 25, 22,  4, 18],
        [18, 14,  2, 29,  4],
        [24,  9, 12, 14, 18],
        [24, 18, 14, 22, 26],
        [27,  2,  9, 23,  3]]])

In [71]:
np.sum(temp2)

702

In [72]:
np.sum(temp2, axis=0)

array([[26, 32, 40,  5, 20],
       [26, 35, 20, 30, 22],
       [26, 12, 29, 29, 23],
       [28, 37, 26, 47, 54],
       [53, 11, 13, 36, 22]])

In [73]:
np.sum(temp2, axis=1)

array([[ 57,  59,  69,  55,  72],
       [102,  68,  59,  92,  69]])

In [76]:
np.sum(temp2, axis=2)

array([[ 45,  66,  42,  88,  71],
       [ 78,  67,  77, 104,  64]])

In [77]:
temp3=np.range(1,17).reshape(2,2,2,2)

AttributeError: module 'numpy' has no attribute 'range'

In [78]:
temp4=np.arange(1,17).reshape(2,2,2,2)

In [79]:
temp4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [80]:
temp4.sum(axis=0)

array([[[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [81]:
temp4.sum(axis=1)

array([[[ 6,  8],
        [10, 12]],

       [[22, 24],
        [26, 28]]])

In [82]:
temp4.sum(axis=2)

array([[[ 4,  6],
        [12, 14]],

       [[20, 22],
        [28, 30]]])

In [83]:
temp4.sum(axis=3)

array([[[ 3,  7],
        [11, 15]],

       [[19, 23],
        [27, 31]]])

In [84]:
np.nan

nan

In [86]:
np.nan==np.nan


False

In [88]:
np.nan is np.nan

True

In [90]:
np.Infinity==np.inf

True

In [91]:
np.Infinity is np.inf

True

In [92]:
np.pi

3.141592653589793

In [95]:
np.sin

<ufunc 'sin'>

In [96]:
## Broadcasting Function

In [97]:
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr2*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [99]:
arr2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
arr2.dot(arr2.T)

array([[14, 32],
       [32, 77]])

In [101]:
arr2@arr2.T

array([[14, 32],
       [32, 77]])

In [102]:
arr2*arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [103]:
arr2+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [104]:
arr2-arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [105]:
np.diag(arr2)

array([1, 5])

In [107]:
np.diag((4,3))

array([[4, 0],
       [0, 3]])

In [109]:
np.diag((4,5,6,7,8))

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])

In [110]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])