In [1]:
print("Hello")

Hello


In [2]:
import numpy as np


In [3]:
np.__version__


'1.16.2'

In [4]:
dataset=np.random.randint(1, 100, 10000)

In [5]:
np.savetxt("sample1.txt",dataset, fmt="%d")

In [6]:
dataset

array([29, 45,  6, ..., 31, 20, 60])

In [7]:
dataset[0]

29

In [9]:
dataset.size

10000

In [10]:
dataset[:100]

array([29, 45,  6, 59, 91, 17, 60, 98, 23, 26, 35, 42, 52, 10,  9, 61, 51,
       12, 39, 54, 60, 65, 91, 95, 20, 71, 90, 22, 71,  2, 15, 35, 65, 76,
       15, 13, 57, 72, 99,  9, 21, 72, 25, 66,  8, 79, 10, 46, 27,  7, 52,
       29, 63, 65, 72, 31, 42, 93, 80, 29, 36, 94, 84, 53, 95, 57, 36, 22,
        8, 49, 77, 30, 86, 76, 99, 87, 77, 24, 97, 13,  9, 29, 13, 75, 60,
       46, 27, 41, 84, 86, 69, 85, 99, 89, 12,  3, 39, 43, 98, 54])

In [12]:
dataset[-100:]

array([96, 62, 86, 78, 26, 16, 25, 89, 24, 10,  5, 64,  6, 99, 35, 43, 33,
       39, 81, 98, 65, 19, 64, 93, 74, 53, 60, 62, 56, 72, 92, 10, 30, 58,
       55, 98, 59, 89, 52, 13, 73, 99, 84,  9,  1, 76, 15, 41, 95, 29, 77,
       38, 27, 64, 91, 18, 95, 29, 57, 69, 16, 93, 37, 11, 96, 24, 87, 15,
       65, 55, 78, 90, 38, 43, 75, 68, 18, 28, 18, 10, 40, 37, 70, 35, 64,
       47,  4,  2, 43, 94, 63, 27, 85, 33, 41, 60, 96, 31, 20, 60])

In [14]:
dataset[dataset.size-100:]

array([96, 62, 86, 78, 26, 16, 25, 89, 24, 10,  5, 64,  6, 99, 35, 43, 33,
       39, 81, 98, 65, 19, 64, 93, 74, 53, 60, 62, 56, 72, 92, 10, 30, 58,
       55, 98, 59, 89, 52, 13, 73, 99, 84,  9,  1, 76, 15, 41, 95, 29, 77,
       38, 27, 64, 91, 18, 95, 29, 57, 69, 16, 93, 37, 11, 96, 24, 87, 15,
       65, 55, 78, 90, 38, 43, 75, 68, 18, 28, 18, 10, 40, 37, 70, 35, 64,
       47,  4,  2, 43, 94, 63, 27, 85, 33, 41, 60, 96, 31, 20, 60])

In [15]:
dataset<10

array([False, False,  True, ..., False, False, False])

In [16]:
dataset[dataset<10]

array([6, 9, 2, 9, 8, 7, 8, 9, 3, 2, 6, 5, 2, 7, 1, 6, 2, 4, 1, 4, 8, 4,
       4, 4, 8, 8, 7, 1, 9, 2, 8, 4, 5, 1, 1, 9, 1, 4, 3, 5, 6, 4, 9, 9,
       2, 6, 2, 8, 8, 9, 7, 3, 3, 4, 6, 6, 6, 1, 9, 4, 9, 3, 8, 7, 7, 4,
       8, 5, 2, 1, 1, 9, 2, 2, 3, 7, 5, 1, 9, 1, 3, 3, 2, 4, 5, 6, 3, 5,
       6, 9, 6, 3, 5, 6, 8, 9, 7, 6, 5, 7, 1, 3, 4, 6, 9, 7, 3, 8, 1, 8,
       3, 2, 3, 9, 7, 3, 3, 9, 1, 3, 5, 5, 8, 1, 7, 1, 5, 2, 3, 4, 3, 4,
       9, 7, 3, 4, 4, 5, 5, 7, 9, 7, 2, 6, 3, 8, 4, 5, 8, 5, 1, 5, 9, 8,
       9, 9, 1, 8, 7, 2, 5, 5, 5, 5, 9, 8, 8, 6, 2, 3, 4, 6, 6, 5, 5, 9,
       3, 3, 7, 5, 5, 7, 3, 1, 3, 2, 6, 6, 2, 6, 8, 4, 7, 7, 9, 3, 6, 7,
       8, 7, 6, 6, 8, 2, 3, 9, 7, 3, 3, 1, 4, 4, 8, 8, 4, 9, 9, 4, 3, 7,
       3, 9, 5, 5, 7, 9, 4, 6, 5, 3, 9, 6, 2, 3, 5, 7, 8, 9, 7, 8, 3, 9,
       4, 7, 7, 6, 9, 5, 3, 2, 6, 9, 7, 1, 8, 9, 4, 9, 2, 9, 6, 1, 1, 5,
       5, 9, 9, 1, 7, 3, 4, 9, 8, 9, 2, 6, 5, 3, 6, 6, 4, 6, 1, 2, 4, 3,
       1, 6, 9, 3, 9, 1, 5, 6, 7, 8, 9, 7, 3, 8, 5,

In [17]:
dataset[(dataset<3) |(dataset>97)]

array([98,  2, 99, 99, 99, 98,  2,  2, 99, 99, 98,  1, 99,  2, 99, 99,  1,
       98, 98, 98, 98,  1,  2,  1,  1,  1, 98,  2,  2, 98, 98, 98,  1, 98,
       98, 98,  2,  1,  1,  2,  2,  1, 98,  1,  2, 99, 99, 99, 98, 98,  1,
       98, 99,  1,  2, 98, 99,  1, 99, 98,  1, 99, 98, 98,  1, 99,  2, 99,
       99, 98,  2,  1,  1,  2, 98, 99, 99, 99,  2, 98, 98, 99, 98, 99, 99,
        1,  2, 99,  2, 99, 99, 99, 98, 99, 99,  2, 98, 99,  1, 98, 98,  2,
       98, 98, 98,  2,  1, 99, 98,  2,  1,  1, 99, 99, 98, 99, 99,  1, 98,
       99,  2,  1,  2, 98, 99,  1,  1, 99, 99,  1,  1, 98,  1,  1,  2, 99,
       98, 99, 99, 99, 98, 99,  1,  2, 99, 99, 99,  1, 99,  1,  1, 98,  2,
       99,  1, 99, 99,  2, 98,  1,  1,  2,  1, 98, 99, 99, 98, 98, 98,  2,
       99,  2, 98, 99, 99,  2,  2,  1,  2, 99, 99,  2, 98,  1,  1,  2, 99,
       98,  2,  2,  2,  2, 99, 98,  2,  1, 99,  1, 99, 98, 98,  1,  1,  1,
        2,  1,  2,  1,  2,  1,  2,  2, 98, 98, 98,  2, 99, 98, 98, 99, 99,
       98, 99, 98, 99,  1

In [18]:
dset1=dataset[dataset<3]

In [19]:
dset1

array([2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2])

In [20]:
dset1.size

176

In [21]:
np.any(dset1)

True

In [22]:
np.all(dset1)

True

In [23]:
np.any(dset1<2)

True

In [24]:
np.all(dset1<2)

False

In [25]:
np.where(dset1<2)

(array([  3,   5,   6,   8,   9,  10,  13,  15,  16,  19,  20,  22,  23,
         25,  26,  27,  30,  31,  34,  38,  41,  43,  44,  45,  47,  49,
         50,  51,  52,  53,  54,  56,  58,  59,  60,  62,  64,  65,  67,
         72,  75,  76,  83,  84,  85,  86,  87,  89,  91,  93,  97,  98,
        100, 103, 104, 106, 107, 108, 110, 111, 113, 114, 115, 116, 120,
        123, 126, 128, 129, 131, 133, 134, 135, 136, 137, 138, 139, 140,
        142, 147, 151, 154, 155, 156, 157, 158, 159, 161, 162, 163, 164,
        165, 167, 168, 170, 171, 172, 173, 174], dtype=int64),)

In [26]:
dset1

array([2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2])

In [27]:
np.where(dset1<2, "one", "two")

array(['two', 'two', 'two', 'one', 'two', 'one', 'one', 'two', 'one',
       'one', 'one', 'two', 'two', 'one', 'two', 'one', 'one', 'two',
       'two', 'one', 'one', 'two', 'one', 'one', 'two', 'one', 'one',
       'one', 'two', 'two', 'one', 'one', 'two', 'two', 'one', 'two',
       'two', 'two', 'one', 'two', 'two', 'one', 'two', 'one', 'one',
       'one', 'two', 'one', 'two', 'one', 'one', 'one', 'one', 'one',
       'one', 'two', 'one', 'two', 'one', 'one', 'one', 'two', 'one',
       'two', 'one', 'one', 'two', 'one', 'two', 'two', 'two', 'two',
       'one', 'two', 'two', 'one', 'one', 'two', 'two', 'two', 'two',
       'two', 'two', 'one', 'one', 'one', 'one', 'one', 'two', 'one',
       'two', 'one', 'two', 'one', 'two', 'two', 'two', 'one', 'one',
       'two', 'one', 'two', 'two', 'one', 'one', 'two', 'one', 'one',
       'one', 'two', 'one', 'one', 'two', 'one', 'one', 'one', 'one',
       'two', 'two', 'two', 'one', 'two', 'two', 'one', 'two', 'two',
       'one', 'two',

In [28]:
def map_nums(val):
    if val==1: return "one"
    elif val==2: return "Two"
    elif val==3: return "Three"
    else:  return "Other"

In [29]:
dset2=dataset[dataset<5]

In [30]:
dset2

array([2, 3, 2, 2, 1, 2, 4, 1, 4, 4, 4, 4, 1, 2, 4, 1, 1, 1, 4, 3, 4, 2,
       2, 3, 3, 4, 1, 4, 3, 4, 2, 1, 1, 2, 2, 3, 1, 1, 3, 3, 2, 4, 3, 3,
       1, 3, 4, 3, 1, 3, 2, 3, 3, 3, 1, 3, 1, 1, 2, 3, 4, 3, 4, 3, 4, 4,
       2, 3, 4, 1, 1, 2, 2, 3, 4, 3, 3, 3, 1, 3, 2, 2, 4, 3, 2, 3, 3, 3,
       1, 4, 4, 4, 4, 3, 3, 4, 3, 2, 3, 3, 4, 3, 2, 1, 4, 2, 1, 1, 1, 3,
       4, 2, 3, 4, 1, 2, 4, 3, 1, 3, 1, 3, 1, 1, 4, 1, 3, 1, 3, 2, 3, 4,
       3, 4, 1, 2, 4, 3, 4, 3, 3, 3, 1, 1, 1, 3, 3, 3, 4, 3, 3, 2, 1, 4,
       4, 2, 4, 3, 3, 4, 1, 1, 3, 4, 2, 1, 3, 4, 2, 4, 4, 4, 2, 3, 4, 2,
       2, 1, 2, 3, 3, 4, 2, 4, 4, 4, 3, 3, 4, 3, 1, 3, 3, 1, 3, 3, 2, 4,
       2, 2, 2, 4, 2, 3, 4, 2, 4, 1, 1, 3, 3, 3, 1, 1, 1, 2, 1, 2, 3, 1,
       3, 2, 4, 3, 4, 1, 2, 3, 2, 2, 4, 3, 3, 1, 3, 1, 2, 3, 1, 2, 3, 3,
       4, 2, 4, 1, 1, 2, 1, 4, 1, 3, 1, 2, 1, 1, 2, 1, 3, 3, 3, 4, 1, 4,
       1, 1, 2, 2, 4, 3, 2, 4, 1, 2, 4, 2, 3, 1, 2, 3, 2, 3, 4, 1, 3, 4,
       3, 4, 2, 4, 4, 3, 4, 3, 1, 1, 2, 3, 4, 1, 3,

In [31]:
mapp=np.vectorize(map_nums)

In [32]:
mapp(dset2)

array(['Two', 'Three', 'Two', 'Two', 'one', 'Two', 'Other', 'one',
       'Other', 'Other', 'Other', 'Other', 'one', 'Two', 'Other', 'one',
       'one', 'one', 'Other', 'Three', 'Other', 'Two', 'Two', 'Three',
       'Three', 'Other', 'one', 'Other', 'Three', 'Other', 'Two', 'one',
       'one', 'Two', 'Two', 'Three', 'one', 'one', 'Three', 'Three',
       'Two', 'Other', 'Three', 'Three', 'one', 'Three', 'Other', 'Three',
       'one', 'Three', 'Two', 'Three', 'Three', 'Three', 'one', 'Three',
       'one', 'one', 'Two', 'Three', 'Other', 'Three', 'Other', 'Three',
       'Other', 'Other', 'Two', 'Three', 'Other', 'one', 'one', 'Two',
       'Two', 'Three', 'Other', 'Three', 'Three', 'Three', 'one', 'Three',
       'Two', 'Two', 'Other', 'Three', 'Two', 'Three', 'Three', 'Three',
       'one', 'Other', 'Other', 'Other', 'Other', 'Three', 'Three',
       'Other', 'Three', 'Two', 'Three', 'Three', 'Other', 'Three', 'Two',
       'one', 'Other', 'Two', 'one', 'one', 'one', 'Three', 'Oth

In [35]:
def m1(arg):
    return arg

In [36]:
def hello(func):
    def wrapper(arg):
        return "Hello"+func(arg)
    return wrapper
    

In [37]:
m2=hello(m1)

In [38]:
m2

<function __main__.hello.<locals>.wrapper(arg)>

In [39]:
m1("World")

'World'

In [40]:
m2(" World")

'HelloWorld'

In [41]:
m2(" World")

'Hello World'

In [42]:
@hello
def m3(arg):
    return arg*3

In [43]:
m3(" world")

'Hello world world world'